# Generated by Django 5.1.4 on 2024-12-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0002_delete_brands_delete_cars"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "brands",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("mileage", models.IntegerField()),
                ("price", models.IntegerField()),
                ("transmission", models.CharField(max_length=50)),
                ("engine_volume", models.CharField(max_length=50)),
                ("drive", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("power_volume", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "cars",
                "managed": False,
            },
        ),
    ]
