# Generated by Django 5.1.4 on 2024-12-20 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
