# Generated by Django 5.1.4 on 2025-01-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
    ]
