# Generated by Django 5.1.4 on 2025-01-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_feedback_clip"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_url", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "clips",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Clip",
        ),
    ]
