# Generated by Django 5.1.4 on 2025-01-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_currencyrate_currency'),
    ]

    operations = [
    ]
