# Generated by Django 5.1.4 on 2025-01-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20250127_1728'),
    ]

    operations = [
    ]
