# Generated by Django 5.1.4 on 2025-01-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_brands_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='brands',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
