# Generated by Django 5.1.4 on 2025-01-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_brands_currency_code_alter_brands_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'managed': True},
        ),
    ]
