# Generated by Django 5.1.4 on 2025-01-30 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_cars_options'),
    ]

    operations = []